version: '3'

services:
    backend:
        container_name: api-name
        restart: always
        build: .
        ports:
            - 10035:5535
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            - PG_USER=roberto_garza
            - PG_PASSWORD=Enroute123
            - PG_DATABASE=roberto_hernandezdb
            - PG_HOST=roberto_garza
        depends_on: 
            - db
        command: npm run dev
    db: 
        container_name: django35
        image: postgres:13
        ports: 
            - 5532:5532
        environment:
            - POSTGRES_DB=roberto_hernandezdb
            - POSTGRES_PASSWORD=Enroute123
            - POSTGRES_USER=roberto_garza
            - POSTGRES_HOST_AUTH_METHOD=trust
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - db-data:/var/lib/postgresql/data/pgdata
        secrets:
            - postgresql_password
volumes:
  db-data:

secrets:
  postgresql_password:
    file: odoo_pg_pass